### ISSUE TITLE
v1.0.1 has bad dependencies

### ISSUE THREAD

**Issue by jvexiau** [devopsfaith/krakend-ratelimit#9]
Hi, 
the new module go compatible version v1.0.1 seems to have wrong dependency : 

	github.com/juju/ratelimit v1.0.2-0.20171026090426-59fac5042749

so when we try do build app : 
`github.com/devopsfaith/krakend-ratelimit@v1.0.0 requires
github.com/juju/ratelimit@v1.0.2-0.20171026090426-59fac5042749: invalid pseudo-version: tag (v1.0.1) found on revision 59fac5042749 is already canonical, so should not be replaced with a pseudo-version derived from that tag`

my workaround is to declare in my go.mod 
`replace github.com/juju/ratelimit v1.0.2-0.20171026090426-59fac5042749 => github.com/juju/ratelimit v1.0.1
`

could you fix the import ? 

thanks,

**Comment by kpacha** [comment]
the problem is reproducible when compiling v1.0.0 on go1.13. I've just pushed the v1.1.0 with this fix and other improvements
